# Generated by Django 3.2.21 on 2023-10-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='answer',
            field=models.TextField(),
        ),
    ]
