# Generated by Django 3.2.21 on 2023-10-02 12:44

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=djrichtextfield.models.RichTextField(max_length=10000),
        ),
    ]
