# Generated by Django 3.2.21 on 2023-10-02 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('article', '0004_auto_20231002_1305'), ('article', '0005_alter_article_entered_by'), ('article', '0006_alter_article_entered_by')]

    dependencies = [
        ('article', '0003_alter_article_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='entered_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='article_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
