# Generated by Django 3.2.21 on 2023-10-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default='https://www.worksheetcloud.com/blog/why-is-reading-important/', max_length=500),
            preserve_default=False,
        ),
    ]
