# Generated by Django 3.2.21 on 2023-10-10 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
