# Generated by Django 3.2.21 on 2023-10-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sort_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sort_price',
        ),
    ]
